# Generated by Django 5.2.1 on 2026-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='picked_up_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='stored_by',
            field=models.CharField(default='系统', max_length=40),
        ),
    ]
