# Generated by Django 5.2.1 on 2026-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_tracking_no', models.CharField(blank=True, max_length=50)),
                ('pickup_code', models.CharField(blank=True, max_length=12)),
                ('exception_type', models.CharField(choices=[('wrong_code', '取件码错误'), ('not_found', '快件不存在'), ('damaged', '快件破损'), ('other', '其他异常')], default='other', max_length=20)),
                ('operator', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '取件异常',
                'verbose_name_plural': '取件异常',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=40)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('inbound_count', models.IntegerField(default=0)),
                ('pickup_exception_count', models.IntegerField(default=0)),
                ('return_processed_count', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('handed_by', models.CharField(max_length=40)),
                ('received_by', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '交接班记录',
                'verbose_name_plural': '交接班记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
